// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID         string   `json:"id"`
	CustomerID *string  `json:"customer_id,omitempty"`
	ProductID  *string  `json:"product_id,omitempty"`
	Quantity   *string  `json:"quantity,omitempty"`
	TotalPrice *float64 `json:"total_price,omitempty"`
	Status     *string  `json:"status,omitempty"`
	CreatedAt  *string  `json:"created_at,omitempty"`
	UpdatedAt  *string  `json:"updated_at,omitempty"`
}

type Query struct {
}
